### ISSUE TITLE
Item_content_recommender does not exist error

### ISSUE THREAD

**Issue by jonflanders** [apple/turicreate#1089]
I'm building an item recommender following the instructions from the docs.

I am getting this error in Xcode "MLModelAsset: load failed with error Error Domain=com.apple.CoreML Code=0 "Error: Unable to load model from data: Class item_content_recommender does not exist." UserInfo={NSLocalizedDescription=Error: Unable to load model from data: Class item_content_recommender does not exist.}"

I have verified that libRecommender.dylib is in my frameworks directory and I can successfully load it using dlopen:
let handle = dlopen("libRecommender.dylib", RTLD_NOW)
		
handle in non-null.

Any suggestions?

**Comment by jonflanders** [comment]
Note I am getting this when I try to load the model definition using coremltools 

"RuntimeError: {
    NSLocalizedDescription = "Error: Unable to load model from data: Class item_content_recommender does not exist.";
}"

**Comment by jonflanders** [comment]
FYI I have gotten passed this issue by cloning the repo and building for iOS and adding both libRecommender.dylib and libunity_shared.dylib to my build.

**Comment by znation** [comment]
Thanks for reporting this @jonflanders! It seems we're missing that class in the `libRecommender.dylib` -- ideally you shouldn't need to include `libunity_shared.dylib` as well. This issue will track that. In the meantime the workaround appears to be including both dylibs.

**Comment by khill25** [comment]
I'm also having this issue but I'm having issues creating the iOS binaries from source. I got the coreml model from my coworker and am trying to get it into a project we are working on. 

`./configure --target-ios`
`cd debug/src/unity`
`sudo make`

Errors out with this:
`[  0%] Performing build step for 'ex_libpng'
libtool: link: gcc -fPIC -I/path-to-my-user/turicreate/deps/local/include -arch arm64 -Wall -g -miphoneos-version-min=12.0 -Wno-c++11-narrowing -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk -o pngunknown contrib/libtests/pngunknown.o  -L/path-to-my-user/turicreate/deps/local/lib ./.libs/libpng16.a -lz
ld: warning: ignoring file contrib/libtests/pngunknown.o, file was built for x86_64 which is not the architecture being linked (arm64): contrib/libtests/pngunknown.o
Undefined symbols for architecture arm64:
  "_main", referenced from:
     implicit entry/start for main executable
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[4]: *** [pngunknown] Error 1
make[3]: *** [all] Error 2
make[2]: *** [../deps/build/libpng/src/ex_libpng-stamp/ex_libpng-build] Error 2
make[1]: *** [CMakeFiles/ex_libpng.dir/all] Error 2
make: *** [all] Error 2`

I couldn't find any specific info about building for ios. How do I fix this?

**Comment by znation** [comment]
@khill25 Try `./build_capi.sh --iOS --release --cleanup` instead. I suspect if you've done an x64 build, you'll need a cleanup in there to remove any non-arm64 pieces, and the `./build_capi.sh` wrapper is better tested than running configure directly.

**Comment by khill25** [comment]
Unfortunately @jonflanders work around didn't work for me. 

Thanks for the step in the right direction on compiling for iOS though.  Had to make a change to the 
`./build_capi.sh`file. It errored out while trying to configure. The `ios_flag=` was set to `--with-ios` but needed `--target-ios` Not sure if I should open a seperate ticket for that bug or not.

**Comment by znation** [comment]
Thanks for pointing that out @khill25 - I put up a fix at https://github.com/apple/turicreate/pull/1223. Why didn't @jonflanders' workaround work for you -- maybe there is another workaround we can provide?

**Comment by khill25** [comment]
Maybe I didn't build all the binaries correctly? I used the libRecommender.dylib from the release page and the built libunity_shared.dylib that was in `release/src/unity` directory after running a make command from there. I don't know where (if) the libRecommender built to.

I embedded both binaries and copied the to bundle resources. 

My coworker hacked together a server side solution that I can access via rest api but I now I want to fix this issue and get it to run locally just for my own satisfaction!

**Comment by znation** [comment]
@khill25 Sorry, the process for building libRecommender is a bit hacky at the moment. In addition to that `./build_capi.sh` step, after that, cd into `release/src/objc` and run `make -j8`. Then you will get a `libRecommender.dylib` in that directory. Try using that one (along with your built `libunity_shared.dylib`) and see if they work together.

**Comment by khill25** [comment]
I created a test project to isolate variables. Fresh single view project, targeting 12.1. Bitcode disabled otherwise I get an error.

I get these messages
`
objc[3234]: Class TCRecommenderOutput is implemented in both /private/var/containers/Bundle/Application/2D89AB5F-2FB7-41AA-A918-A72E6F4AF2F3/coremltest.app/Frameworks/libunity_shared.dylib (0x10726bc18) and /private/var/containers/Bundle/Application/2D89AB5F-2FB7-41AA-A918-A72E6F4AF2F3/coremltest.app/Frameworks/libRecommender.dylib (0x105a02050). One of the two will be used. Which one is undefined.
objc[3234]: Class TCRecommender is implemented in both /private/var/containers/Bundle/Application/2D89AB5F-2FB7-41AA-A918-A72E6F4AF2F3/coremltest.app/Frameworks/libunity_shared.dylib (0x10726bc40) and /private/var/containers/Bundle/Application/2D89AB5F-2FB7-41AA-A918-A72E6F4AF2F3/coremltest.app/Frameworks/libRecommender.dylib (0x105a02078). One of the two will be used. Which one is undefined.
objc[3234]: Class DummyThread is implemented in both /private/var/containers/Bundle/Application/2D89AB5F-2FB7-41AA-A918-A72E6F4AF2F3/coremltest.app/Frameworks/libunity_shared.dylib (0x10726bbc8) and /private/var/containers/Bundle/Application/2D89AB5F-2FB7-41AA-A918-A72E6F4AF2F3/coremltest.app/Frameworks/libRecommender.dylib (0x105a020f0). One of the two will be used. Which one is undefined.
`

**Comment by znation** [comment]
@khill25 Strange, I'm not sure why you'd be having that issue on your original project but not the test project. The warnings about symbols being included from two dylibs is expected, and can be safely ignored as long as you're using the two dylibs built from the same commit/with the same flags. Sounds like the original issue here (item_content_recommender not found) is solved at least for your test project.

**Comment by khill25** [comment]
I figured the warnings could be ignored. Was nice to not see a crash there. I still don't understand what's causing it to break on my original project.

**Comment by hoytak** [comment]
Closing this issue for now; reopen if the fix has further issues.

**Comment by dogahe** [comment]
I have the same issue. I have trained a `model = tc.recommender.item_content_recommender.create` and I have brought it in in the Xcode project and have included `libRecommender.dylip`. I get the error:  `Unable to load model from data: Class item_content_recommender does not exist." UserInfo={NSLocalizedDescription=Error: Unable to load model from data: Class item_content_recommender does not exist.}` What's the best solution?

**Comment by znation** [comment]
Reactivating per @dogahe's feedback. @hoytak, is this expected behavior? Did a fix go in at some point that should change this behavior?
